solc_path: "solc"
detectors:
  slither_cmd: "slither"
  securify_cmd: "securify"
  ilf_cmd: "ilf"
  rsymx_cmd: "rsymx"
  smartfast_cmd: "smartfast"
  vulhunter_cmd: "vulhunter"
weights_path: "../Detection_weights/default.yaml"

reward:
  w_bug_removed: 0.5
  w_no_new_bugs: 0.2
  w_compile_ok: 0.1
  w_symexec_ok: 0.1
  w_gas_struct: 0.1

gas_similarity:
  leven_threshold: 0.4
  max_gas_penalty: 0.1
